FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl

# 1. Install pnpm first (this layer will be cached)
RUN npm install -g pnpm

# 2. Copy only lockfiles
COPY package.json pnpm-lock.yaml* ./

# 3. Install dependencies
RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

RUN mkdir -p logs

EXPOSE 5000

CMD ["pnpm", "start"]
